host: ENC[AES256_GCM,data:8pUWoAPBYw+FuvCBfg==,iv:EKqfndhgIAZPcemMLGv8JI+XZIPsP59kyeYeAtkLmpM=,tag:BP6qshJZuUk580fqVgrzXg==,type:str]
admin_user: ENC[AES256_GCM,data:16r48A==,iv:6hs7sX3aod2ffmgLGfwh8Bfl1mCeWxhHV9Nn8Lcmky0=,tag:7UcKjUxBfi+0sw3QXS9hGA==,type:str]
domain: ENC[AES256_GCM,data:8vatyTv1p85GcmGRT06Hb34=,iv:YqWRfkXtTc8pK2kQdYxYvndv1z/eAc1Pf3ug35SrMFE=,tag:maPlIeUg5zIUzwilHiMTTA==,type:str]
authorized_key: ENC[AES256_GCM,data:pVdXfGqwnBQtBzST8XGZwk13Gz5YPzRXz7KrlobGu6UKqzNFD9WqaTm0hmqQET/rWiQfdOYp7yZNpkvkKBEiz01U5S+QzSXgAjfoFCm608I0ctqdBnPMn0/GJTeuXEchgQ==,iv:/6ogmI5DaBu0z8gCyA1J6yF41aXnVCYwlnJgqewkEL0=,tag:ku2Dc6kkTbs8hIN8p0Oevw==,type:str]
backup_recipient: ENC[AES256_GCM,data:IQrqxzq+Gma7FsJ8BphxXX1srE7Mh7+ks4posWjQTfL7qB8DRxgsz9/OgmbD7SIUJAAd5WLALJolAvq6JWU=,iv:SUcE7zw8pfAmhYHZdWlEGh76f+GOZ8aX41SvoQY5lGQ=,tag:4wROWeZkiBuOCkCBxg0V7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZktpSmY0Z1VNTnNHS1NU
            MjMrYTFPUFR2SnZ4cDNVeDltZ2d5WWxjQlNZCjlwSWNTclVZNVNnM1RybTBDbEtw
            cDRUSzd3cXd2RXNyaWxWM1JQdHcvL2cKLS0tIGxiN3JsNmlkQ3JuN1dBMTJST24w
            SUF5QjJLZWlTaHk3bzVJeE9WbE9tTG8KXiGLZyrhdfbdu8gTb1eVbkHgIm9wEM/o
            Hs2UJygpDUnt5e2g+jbzI7r5eNTizwaGSpp7wqiWK8TkBnOqsSty8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wwf8jfxffrqzdd9ntxsry4c3n2rddta036fj5nlu0qhacxmeu52sj3u3yg
    lastmodified: "2026-10-02T19:06:03Z"
    mac: ENC[AES256_GCM,data:g2dvUs65Nf1b+c8l4lCTcSHhqw+YjdY91eC4OO3O2TnRqpisIEfBKHdhk9exHLUNrMnbFmS+jYDd+2LtCHdTqAlsqS7vu4yXbwrKF8FQJ9+133rFxL8jM/qTjqP6H6KGPXo6rRNeSSEQY4SiC1WXoI8XQINclHkJeNRVgKo7Szc=,iv:Yievb6gmDycO6GKcCVwLlqkxxuXRC/3UJrnpCSam5fM=,tag:2btEqmLV3h2/U9imESf5Rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
