---
- name: Restart vaultwarden
  community.docker.docker_compose_v2:
    project_src: /opt/vaultwarden
    state: present
    restarted: true
    services:
      - vaultwarden
  environment:
    COMPOSE_PROJECT_NAME: vaultwarden
  become: true
  become_user: op
  no_log: true

- name: Reload caddy
  community.docker.docker_container_exec:
    container: vaultwarden-caddy-1
    command: caddy reload -c /etc/caddy/Caddyfile
  become: true
  become_user: op
  register: caddy_reload
  failed_when: caddy_reload.rc != 0
  changed_when: true
