---
- name: Molyanov config changed
  ansible.builtin.debug:
    msg: "molyanov global.yml rendered successfully"

- name: Molyanov hook installed
  ansible.builtin.debug:
    msg: "molyanov hook installed successfully"
